### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by bananabot1024** [bananabot1024/USACO-Training#1]
## Section 1.1
- [x] text: submitting solutions
- [x] prob: ride
- [x] text: problem types
- [x] text: ad hoc problems
- [x] prob: gift1
- [ ] prob: friday
- [ ] prob: beads
